// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EligibleService.Claim.RealtimeClaims
{

    public class Amount : Quantity
    {

        [JsonProperty("patient_responsibility")]
        public int PatientResponsibility { get; set; }
    }

}
