//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EligibleService.Net {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EligibleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EligibleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EligibleService.Net.EligibleResources", typeof(EligibleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gds.eligibleapi.com/.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acknowledgements.
        /// </summary>
        internal static string ClaimAcknowledgementsPath {
            get {
                return ResourceManager.GetString("ClaimAcknowledgementsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /coverage/cost_estimates.
        /// </summary>
        internal static string CostEstimates {
            get {
                return ResourceManager.GetString("CostEstimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /payers/eligibility.
        /// </summary>
        internal static string CoveragePayers {
            get {
                return ResourceManager.GetString("CoveragePayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /payers/claims/era.
        /// </summary>
        internal static string ElectronicRemittanceAdvicePayers {
            get {
                return ResourceManager.GetString("ElectronicRemittanceAdvicePayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /enrollment_npis.
        /// </summary>
        internal static string EnrollmentNpis {
            get {
                return ResourceManager.GetString("EnrollmentNpis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inquiry.
        /// </summary>
        internal static string Inquiry {
            get {
                return ResourceManager.GetString("Inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to original_signature_pdf.
        /// </summary>
        internal static string OriginalSignaturePdf {
            get {
                return ResourceManager.GetString("OriginalSignaturePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /coverage/all.
        /// </summary>
        internal static string PathToAllCoverages {
            get {
                return ResourceManager.GetString("PathToAllCoverages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /claims.
        /// </summary>
        internal static string PathToClaims {
            get {
                return ResourceManager.GetString("PathToClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /customers.
        /// </summary>
        internal static string PathToCustomers {
            get {
                return ResourceManager.GetString("PathToCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /payers/deprecate.
        /// </summary>
        internal static string PathToDeprecatedPrayers {
            get {
                return ResourceManager.GetString("PathToDeprecatedPrayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /coverage/medicare.
        /// </summary>
        internal static string PathToMedicare {
            get {
                return ResourceManager.GetString("PathToMedicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /payers/.
        /// </summary>
        internal static string PathToPayerById {
            get {
                return ResourceManager.GetString("PathToPayerById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /payers.
        /// </summary>
        internal static string PathToPayers {
            get {
                return ResourceManager.GetString("PathToPayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /payers/search_options.
        /// </summary>
        internal static string PathToPayerSearchOptions {
            get {
                return ResourceManager.GetString("PathToPayerSearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /payers/status.
        /// </summary>
        internal static string PathtoPayersStatus {
            get {
                return ResourceManager.GetString("PathtoPayersStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /status.
        /// </summary>
        internal static string PayerStatus {
            get {
                return ResourceManager.GetString("PayerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment_reports.
        /// </summary>
        internal static string PaymentReports {
            get {
                return ResourceManager.GetString("PaymentReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /payment/status.
        /// </summary>
        internal static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /payers/claims/payment/status.
        /// </summary>
        internal static string PaymentStatusPayers {
            get {
                return ResourceManager.GetString("PaymentStatusPayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /precert.
        /// </summary>
        internal static string Precert {
            get {
                return ResourceManager.GetString("Precert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to realtime.
        /// </summary>
        internal static string Realtime {
            get {
                return ResourceManager.GetString("Realtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to received_pdf.
        /// </summary>
        internal static string ReceivedPdf {
            get {
                return ResourceManager.GetString("ReceivedPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /referral/create.
        /// </summary>
        internal static string ReferralCreate {
            get {
                return ResourceManager.GetString("ReferralCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /referral/inquiry.
        /// </summary>
        internal static string ReferralInquiry {
            get {
                return ResourceManager.GetString("ReferralInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /search_options.
        /// </summary>
        internal static string SearchOptions {
            get {
                return ResourceManager.GetString("SearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.5.
        /// </summary>
        internal static string SupportedApiVersion {
            get {
                return ResourceManager.GetString("SupportedApiVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to v1.5.
        /// </summary>
        internal static string LibraryVersion
        {
            get
            {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }

        internal static string Fingerprint
        {
            get
            {
                return ResourceManager.GetString("Fingerprint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 4B2C6888EDE79D0EE47339DC6FAB5A6D0DC3CB0E.
        /// </summary>
        internal static string SecondaryFingerprint
        {
            get
            {
                return ResourceManager.GetString("SecondaryFingerprint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to gds.eligibleapi.com, eligible.com.
        /// </summary>
        internal static string WhiteListedDomain
        {
            get
            {
                return ResourceManager.GetString("WhiteListedDomain", resourceCulture);
            }
        }
    }
}
